name = str(input('write your name: ')).strip()
print('analyzing...' )
print('your name has silva?')
print('silva' in name.lower())
print('your name has santos?')
print('santos' in name.lower())
print('your name has carvalho?')
print('carvalho' in name.lower())
print('your name has alves?')
print('alves' in name.lower())
