n = int(input('digite um numero: '))
print('_'*12)
print('{} x 1 = {}'.format(n, n*1))
print('{} x 2 = {}'.format(n , n*2))
print('{} x 3 = {}'.format(n, n*3))
print('{} x 4 = {}'.format(n, n*4))
print('{} x 5 = {}'.format(n, n*5))
print('{} x 6 = {}'.format(n , n*6))
print('{} x 7 = {}'.format(n, n*7))
print('{} x 8 = {}'.format(n, n*8))
print('{} x 9 = {}'.format(n, n*8))
print('{} x 10 + {}'.format(n, n*10))
print('_'*12)
#for i in range(10):
#   print(f'{n} X {i} = {n * i}')
